{

"name":"config-server",
"profiles":["default"],
"label":null,
"version":""
"state":null,
"propertySources":[
{
"name":"https://github.com/microserviceforsubmit/cloud-config-file/blob/main/application.yml",
"source":{
	"welcome":"WELLCOME"
}
}
]
}
